name: CI
on: push
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Setup
        run: npm ci
      - name: Test
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI